POST http://localhost:1911/auth/login
Content-Type: application/json

{
  "email": "test46@test.com",
  "password": "nKZesAfvIA"
}

###

POST http://localhost:1911/auth/regenerate-authtoken
Content-Type: application/json

{
  "authToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlN2ExNmE5YzI4Yjc4MTRlODJmMmQzZCIsImlhdCI6MTU4NTU0MzQ0NiwiZXhwIjoxNTg1NjI5ODQ2fQ.sQO3F6SLuDNO5rryj0lgd-3qme6ItveKpTmQD_aF9D4",
  "refreshToken": "TZuYL2P3D4"
}

###

GET http://localhost:1911/auth/user
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlN2ExNmE5YzI4Yjc4MTRlODJmMmQzZCIsImlhdCI6MTU4NTU0MzQ0NiwiZXhwIjoxNTg1NjI5ODQ2fQ.sQO3F6SLuDNO5rryj0lgd-3qme6ItveKpTmQD_aF9D4

###