GET http://localhost:1911/users

###

POST http://localhost:1911/users
Content-Type: application/json

{
  "fName": "Test2",
  "lName": "Test11",
  "email": "test38@test.com",
  "sendInvite": true
}

###
